// Implementation file for parser generated by fsyacc
#nowarn "64";; // turn off warnings that type variables used in production annotations are instantiated to concrete type
open FSharp.Text.Lexing
open FSharp.Text.Parsing.ParseHelpers
# 1 "SpreadsheetParser.fsy"

open SpreadsheetLexer
module SpreadsheetParser

type Expr =
    | Number of float
    | Cell of string
    | Add of Expr * Expr
    | Sub of Expr * Expr
    | Mul of Expr * Expr
    | Div of Expr * Expr

# 18 "SpreadsheetParser.fs"
// This type is the type of tokens accepted by the parser
type token = 
  | EOF
  | ASSIGN
  | PLUS
  | MINUS
  | TIMES
  | DIVIDE
  | LPAREN
  | RPAREN
  | CELLNAME of (string)
  | NUMBER of (float)
// This type is used to give symbolic names to token indexes, useful for error messages
type tokenId = 
    | TOKEN_EOF
    | TOKEN_ASSIGN
    | TOKEN_PLUS
    | TOKEN_MINUS
    | TOKEN_TIMES
    | TOKEN_DIVIDE
    | TOKEN_LPAREN
    | TOKEN_RPAREN
    | TOKEN_CELLNAME
    | TOKEN_NUMBER
    | TOKEN_end_of_input
    | TOKEN_error
// This type is used to give symbolic names to token indexes, useful for error messages
type nonTerminalId = 
    | NONTERM__startstatement
    | NONTERM_statement
    | NONTERM_expr

// This function maps tokens to integer indexes
let tagOfToken (t:token) = 
  match t with
  | EOF  -> 0 
  | ASSIGN  -> 1 
  | PLUS  -> 2 
  | MINUS  -> 3 
  | TIMES  -> 4 
  | DIVIDE  -> 5 
  | LPAREN  -> 6 
  | RPAREN  -> 7 
  | CELLNAME _ -> 8 
  | NUMBER _ -> 9 

// This function maps integer indexes to symbolic token ids
let tokenTagToTokenId (tokenIdx:int) = 
  match tokenIdx with
  | 0 -> TOKEN_EOF 
  | 1 -> TOKEN_ASSIGN 
  | 2 -> TOKEN_PLUS 
  | 3 -> TOKEN_MINUS 
  | 4 -> TOKEN_TIMES 
  | 5 -> TOKEN_DIVIDE 
  | 6 -> TOKEN_LPAREN 
  | 7 -> TOKEN_RPAREN 
  | 8 -> TOKEN_CELLNAME 
  | 9 -> TOKEN_NUMBER 
  | 12 -> TOKEN_end_of_input
  | 10 -> TOKEN_error
  | _ -> failwith "tokenTagToTokenId: bad token"

/// This function maps production indexes returned in syntax errors to strings representing the non terminal that would be produced by that production
let prodIdxToNonTerminal (prodIdx:int) = 
  match prodIdx with
    | 0 -> NONTERM__startstatement 
    | 1 -> NONTERM_statement 
    | 2 -> NONTERM_expr 
    | 3 -> NONTERM_expr 
    | 4 -> NONTERM_expr 
    | 5 -> NONTERM_expr 
    | 6 -> NONTERM_expr 
    | 7 -> NONTERM_expr 
    | 8 -> NONTERM_expr 
    | 9 -> NONTERM_expr 
    | _ -> failwith "prodIdxToNonTerminal: bad production index"

let _fsyacc_endOfInputTag = 12 
let _fsyacc_tagOfErrorTerminal = 10

// This function gets the name of a token as a string
let token_to_string (t:token) = 
  match t with 
  | EOF  -> "EOF" 
  | ASSIGN  -> "ASSIGN" 
  | PLUS  -> "PLUS" 
  | MINUS  -> "MINUS" 
  | TIMES  -> "TIMES" 
  | DIVIDE  -> "DIVIDE" 
  | LPAREN  -> "LPAREN" 
  | RPAREN  -> "RPAREN" 
  | CELLNAME _ -> "CELLNAME" 
  | NUMBER _ -> "NUMBER" 

// This function gets the data carried by a token as an object
let _fsyacc_dataOfToken (t:token) = 
  match t with 
  | EOF  -> (null : System.Object) 
  | ASSIGN  -> (null : System.Object) 
  | PLUS  -> (null : System.Object) 
  | MINUS  -> (null : System.Object) 
  | TIMES  -> (null : System.Object) 
  | DIVIDE  -> (null : System.Object) 
  | LPAREN  -> (null : System.Object) 
  | RPAREN  -> (null : System.Object) 
  | CELLNAME _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | NUMBER _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
let _fsyacc_gotos = [| 0us;65535us;1us;65535us;0us;1us;7us;65535us;3us;4us;11us;5us;12us;6us;13us;7us;14us;8us;15us;9us;16us;10us;|]
let _fsyacc_sparseGotoTableRowOffsets = [|0us;1us;3us;|]
let _fsyacc_stateToProdIdxsTableElements = [| 1us;0us;1us;0us;1us;1us;1us;1us;5us;1us;2us;3us;4us;5us;5us;2us;2us;3us;4us;5us;5us;2us;3us;3us;4us;5us;5us;2us;3us;4us;4us;5us;5us;2us;3us;4us;5us;5us;5us;2us;3us;4us;5us;6us;5us;2us;3us;4us;5us;7us;1us;2us;1us;3us;1us;4us;1us;5us;1us;6us;1us;7us;1us;7us;1us;8us;1us;9us;|]
let _fsyacc_stateToProdIdxsTableRowOffsets = [|0us;2us;4us;6us;8us;14us;20us;26us;32us;38us;44us;50us;52us;54us;56us;58us;60us;62us;64us;66us;|]
let _fsyacc_action_rows = 20
let _fsyacc_actionTableElements = [|1us;32768us;8us;2us;0us;49152us;1us;32768us;1us;3us;4us;32768us;3us;15us;6us;16us;8us;19us;9us;18us;4us;16385us;2us;11us;3us;12us;4us;13us;5us;14us;2us;16386us;4us;13us;5us;14us;2us;16387us;4us;13us;5us;14us;0us;16388us;0us;16389us;0us;16390us;5us;32768us;2us;11us;3us;12us;4us;13us;5us;14us;7us;17us;4us;32768us;3us;15us;6us;16us;8us;19us;9us;18us;4us;32768us;3us;15us;6us;16us;8us;19us;9us;18us;4us;32768us;3us;15us;6us;16us;8us;19us;9us;18us;4us;32768us;3us;15us;6us;16us;8us;19us;9us;18us;4us;32768us;3us;15us;6us;16us;8us;19us;9us;18us;4us;32768us;3us;15us;6us;16us;8us;19us;9us;18us;0us;16391us;0us;16392us;0us;16393us;|]
let _fsyacc_actionTableRowOffsets = [|0us;2us;3us;5us;10us;15us;18us;21us;22us;23us;24us;30us;35us;40us;45us;50us;55us;60us;61us;62us;|]
let _fsyacc_reductionSymbolCounts = [|1us;3us;3us;3us;3us;3us;2us;3us;1us;1us;|]
let _fsyacc_productionToNonTerminalTable = [|0us;1us;2us;2us;2us;2us;2us;2us;2us;2us;|]
let _fsyacc_immediateActions = [|65535us;49152us;65535us;65535us;65535us;65535us;65535us;65535us;65535us;65535us;65535us;65535us;65535us;65535us;65535us;65535us;65535us;16391us;16392us;16393us;|]
let _fsyacc_reductions = lazy [|
# 138 "SpreadsheetParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> string * Expr in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                      raise (FSharp.Text.Parsing.Accept(Microsoft.FSharp.Core.Operators.box _1))
                   )
                 : 'gentype__startstatement));
# 147 "SpreadsheetParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> string in
            let _3 = parseState.GetInput(3) :?> Expr in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 30 "SpreadsheetParser.fsy"
                                                  (_1, _3) 
                   )
# 30 "SpreadsheetParser.fsy"
                 : string * Expr));
# 159 "SpreadsheetParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> Expr in
            let _3 = parseState.GetInput(3) :?> Expr in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 34 "SpreadsheetParser.fsy"
                                              Add(_1, _3) 
                   )
# 34 "SpreadsheetParser.fsy"
                 : Expr));
# 171 "SpreadsheetParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> Expr in
            let _3 = parseState.GetInput(3) :?> Expr in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 35 "SpreadsheetParser.fsy"
                                              Sub(_1, _3) 
                   )
# 35 "SpreadsheetParser.fsy"
                 : Expr));
# 183 "SpreadsheetParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> Expr in
            let _3 = parseState.GetInput(3) :?> Expr in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 36 "SpreadsheetParser.fsy"
                                              Mul(_1, _3) 
                   )
# 36 "SpreadsheetParser.fsy"
                 : Expr));
# 195 "SpreadsheetParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> Expr in
            let _3 = parseState.GetInput(3) :?> Expr in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 37 "SpreadsheetParser.fsy"
                                              Div(_1, _3) 
                   )
# 37 "SpreadsheetParser.fsy"
                 : Expr));
# 207 "SpreadsheetParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = parseState.GetInput(2) :?> Expr in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 38 "SpreadsheetParser.fsy"
                                                     Sub(Number 0.0, _1) 
                   )
# 38 "SpreadsheetParser.fsy"
                 : Expr));
# 218 "SpreadsheetParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = parseState.GetInput(2) :?> Expr in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 39 "SpreadsheetParser.fsy"
                                                  _1 
                   )
# 39 "SpreadsheetParser.fsy"
                 : Expr));
# 229 "SpreadsheetParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> float in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 40 "SpreadsheetParser.fsy"
                                                  Number _1 
                   )
# 40 "SpreadsheetParser.fsy"
                 : Expr));
# 240 "SpreadsheetParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> string in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 41 "SpreadsheetParser.fsy"
                                                  Cell _1 
                   )
# 41 "SpreadsheetParser.fsy"
                 : Expr));
|]
# 252 "SpreadsheetParser.fs"
let tables : FSharp.Text.Parsing.Tables<_> = 
  { reductions = _fsyacc_reductions.Value;
    endOfInputTag = _fsyacc_endOfInputTag;
    tagOfToken = tagOfToken;
    dataOfToken = _fsyacc_dataOfToken; 
    actionTableElements = _fsyacc_actionTableElements;
    actionTableRowOffsets = _fsyacc_actionTableRowOffsets;
    stateToProdIdxsTableElements = _fsyacc_stateToProdIdxsTableElements;
    stateToProdIdxsTableRowOffsets = _fsyacc_stateToProdIdxsTableRowOffsets;
    reductionSymbolCounts = _fsyacc_reductionSymbolCounts;
    immediateActions = _fsyacc_immediateActions;
    gotos = _fsyacc_gotos;
    sparseGotoTableRowOffsets = _fsyacc_sparseGotoTableRowOffsets;
    tagOfErrorTerminal = _fsyacc_tagOfErrorTerminal;
    parseError = (fun (ctxt:FSharp.Text.Parsing.ParseErrorContext<_>) -> 
                              match parse_error_rich with 
                              | Some f -> f ctxt
                              | None -> parse_error ctxt.Message);
    numTerminals = 13;
    productionToNonTerminalTable = _fsyacc_productionToNonTerminalTable  }
let engine lexer lexbuf startState = tables.Interpret(lexer, lexbuf, startState)
let statement lexer lexbuf : string * Expr =
    engine lexer lexbuf 0 :?> _
